version: '3.1'

services:
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 123456
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
    driver: local
